import 'dart:io';
import 'dart:math';
import 'dart:ui';

import 'package:android_intent_plus/android_intent.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:google_mlkit_text_recognition/google_mlkit_text_recognition.dart';
import 'package:image_picker/image_picker.dart';
import 'package:mobile_scanner/mobile_scanner.dart' show MobileScanner;
import 'package:salah_snap_version_second/index.dart';
import 'package:salah_snap_version_second/l10n/app_localizations.dart';
import 'package:salah_snap_version_second/pages/meals/dashboard/ImageToImage.dart';
import 'package:salah_snap_version_second/pages/meals/dashboard/laguage-Page.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/flutter_flow/flutter_flow_widgets.dart';
import 'dart:ui';
import '/custom_code/actions/index.dart' as actions;
import '/custom_code/widgets/index.dart' as custom_widgets;
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'dashboard_model.dart';
export 'dashboard_model.dart';
import 'package:image/image.dart' as img;

class DashboardWidget extends StatefulWidget {
  const DashboardWidget({super.key});

  static String routeName = 'Dashboard';
  static String routePath = 'dashboard';

  @override
  State<DashboardWidget> createState() => _DashboardWidgetState();
}

class _DashboardWidgetState extends State<DashboardWidget> {
  late DashboardModel _model;
  String extractedText = '';
  Future<void> setPrayerAlarms() async {
    final prefs = await SharedPreferences.getInstance();
    List<String> alarms = [];

    for (final entry in _prayerTimes.entries) {
      if (entry.value.isEmpty) continue;

      final parts = entry.value.split(":");
      if (parts.length != 2) continue;

      int hour = int.parse(parts[0]);
      int minute = int.parse(parts[1]);

      final intent = AndroidIntent(
        action: 'android.intent.action.SET_ALARM',
        arguments: {
          'android.intent.extra.alarm.HOUR': hour,
          'android.intent.extra.alarm.MINUTES': minute,
          'android.intent.extra.alarm.MESSAGE': '${entry.key} Prayer',
          'android.intent.extra.alarm.SKIP_UI': true,
        },
      );

      await intent.launch();
      alarms.add("${entry.key}: ${entry.value}");
      await Future.delayed(const Duration(milliseconds: 800));
    }

    await prefs.setStringList("set_alarms", alarms);

    setState(() {
      _setAlarms = alarms;
    });
  }

  Future<void> savePrayerTimesToFirebase() async {
    final user = FirebaseAuth.instance.currentUser;

    if (user == null) {
      debugPrint("⚠️ Skipping Firebase save (user not logged in)");
      return;
    }

    await FirebaseFirestore.instance
        .collection("prayer_times")
        .doc(user.uid)
        .set({
      ..._prayerTimes,
      "createdAt": FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));

    debugPrint("✅ Prayer times saved to Firebase");
  }

  Future<void> openQRScanner() async {
    final result = await Navigator.push(
      context,
      MaterialPageRoute(builder: (_) => const PrayerQRScanner()),
    );

    if (result != null && result is String) {
      await fetchPrayerTimesFromFirebase(result);
    }
  }

  Future<void> fetchPrayerTimesFromFirebase(String qrValue) async {
    try {
      qrValue = qrValue.trim();

      // ✅ Extract ID from Google Drive URL
      String mosqueId = qrValue;
      if (qrValue.contains('/')) {
        mosqueId = qrValue.split('/').last;
      }

      print("🆔 Extracted Mosque ID: $mosqueId");

      final docRef =
          FirebaseFirestore.instance.collection('mosques').doc(mosqueId);

      final doc = await docRef.get();

      // 🟢 IF DOCUMENT DOES NOT EXIST → CREATE IT
      if (!doc.exists) {
        print("⚠️ Mosque not found → creating default data");

        await docRef.set({
          "fajr": "06:15",
          "zuhr": "01:00",
          "asr": "03:45",
          "maghrib": "05:06",
          "isha": "07:00",
          "createdAt": FieldValue.serverTimestamp(),
          "autoGenerated": true,
        });

        print("✅ Mosque auto-created in Firestore");
      }

      // 🔄 FETCH AGAIN (after create OR if already existed)
      final freshDoc = await docRef.get();
      final data = freshDoc.data()!;

      setState(() {
        _prayerTimes['Fajr'] = data['fajr'] ?? '';
        _prayerTimes['Dhuhr'] = data['zuhr'] ?? '';
        _prayerTimes['Asr'] = data['asr'] ?? '';
        _prayerTimes['Maghrib'] = data['maghrib'] ?? '';
        _prayerTimes['Isha'] = data['isha'] ?? '';
      });

      print("✅ Prayer times loaded");
      showPrayerTimesPopup(); // 🔥 popup guaranteed
    } catch (e) {
      print("🔥 Error fetching/creating mosque: $e");
    }
  }

  final List<Map<String, String>> _prayerOrder = [
    {'key': 'Fajr', 'name': 'Fajr'},
    {'key': 'Dhuhr', 'name': 'Dhuhr'},
    {'key': 'Asr', 'name': 'Asr'},
    {'key': 'Maghrib', 'name': 'Maghrib'},
    {'key': 'Isha', 'name': 'Isha'},
    {'key': 'Jumuah', 'name': 'Jumuah'},
  ];
  final Map<String, String> _prayerTimes = {
    "Fajr": "",
    "Dhuhr": "",
    "Asr": "",
    "Maghrib": "",
    "Isha": "",
    "Jumuah": "",
  };

  Future<void> _pickImage(ImageSource source) async {
    final picker = ImagePicker();
    final pickedFile = await picker.pickImage(source: source);

    if (pickedFile != null) {
      final inputImage = InputImage.fromFile(File(pickedFile.path));
      final textRecognizer = TextRecognizer();
      final RecognizedText recognizedText =
          await textRecognizer.processImage(inputImage);

      setState(() {
        extractedText = recognizedText.text;
      });
    }
  }

  File? _image;
  String _text = "";

  // Display order
  void showPrayerTimesPopup() {
    showDialog(
      context: context,
      builder: (_) => AlertDialog(
        title: Text(
          AppLocalizations.of(context)!.prayerTimesTitle,
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: _prayerTimes.entries.map((e) {
            return Padding(
              padding: const EdgeInsets.symmetric(vertical: 4),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(e.key,
                      style: const TextStyle(fontWeight: FontWeight.bold)),
                  Text(e.value),
                ],
              ),
            );
          }).toList(),
        ),
        actions: [
          TextButton(
            onPressed: () {
              Navigator.pop(context);
              setPrayerAlarms();
            },
            child: const Text("Set Alarms"),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text("Close"),
          ),
        ],
      ),
    );
  }

  final Map<String, String?> prayerTimes = {
    "Fajr": null,
    "Dhuhr": null,
    "Asr": null,
    "Maghrib": null,
    "Isha": null,
  };

  /// ⬇️ Show camera/gallery selector
  Future<void> _showImageSourceDialog() async {
    showModalBottomSheet(
      backgroundColor: FlutterFlowTheme.of(context).primary,
      context: context,
      builder: (_) => SafeArea(
        child: Wrap(
          children: [
            ListTile(
              leading: const Icon(Icons.camera_alt),
              title: Text(
                AppLocalizations.of(context)!.camera,
              ),
              onTap: () async {
                print("📷 Opening camera for QR scan");
                Navigator.of(context).pop(); // bottom sheet close
                await openQRScanner(); // QR scanner open
              },
            ),
            ListTile(
              leading: const Icon(Icons.photo_library),
              title: Text(AppLocalizations.of(context)!.gallery),
              onTap: () {
                Navigator.of(context).pop();
                pickImage(ImageSource.gallery);
              },
            ),
          ],
        ),
      ),
    );
  }

  /// ⬇️ Pick image & perform full OCR + parsing
  Future<void> pickImage(ImageSource source) async {
    final picker = ImagePicker();
    final pickedFile = await picker.pickImage(source: source);

    if (pickedFile != null) {
      // Convert to grayscale
      File grayImage = await convertToGrayscale(File(pickedFile.path));

      // Show image in dialog immediately
      await showDialog(
        context: context,
        builder: (context) {
          final PageController pageController = PageController();
          int currentPage = 0;
          String extractedText = "";

          return StatefulBuilder(
            builder: (context, setState) {
              return AlertDialog(
                title: currentPage == 1
                    ? Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(AppLocalizations.of(context)!.setAlarm),
                          ElevatedButton(
                            style: ElevatedButton.styleFrom(
                              backgroundColor:
                                  FlutterFlowTheme.of(context).primary,
                              foregroundColor: Colors.white,
                            ),
                            onPressed: () async {
                              await setPrayerAlarms();
                              if (context.mounted) {
                                Navigator.of(context).pop(); // ✅ Close popup
                              }
                            },
                            child:
                                Text(AppLocalizations.of(context)!.setAlarms),
                          ),
                        ],
                      )
                    : Padding(
                        padding: const EdgeInsets.all(13),
                        child: const Text("Captured Image"),
                      ),

                content: SizedBox(
                  height: 400, // ✅ Fixed height
                  width: 300,
                  child: PageView(
                    controller: pageController,
                    onPageChanged: (index) {
                      setState(() => currentPage = index);
                    },
                    children: [
                      // Page 1: Image preview
                      Column(
                        children: [
                          const Text("Step 1: Image Preview"),
                          const SizedBox(height: 10),
                          SizedBox(
                            height: 250, // ✅ Fixed height instead of Expanded
                            child: Image.file(grayImage),
                          ),
                          const SizedBox(height: 10),
                          Row(
                            children: [
                              Expanded(
                                child: ElevatedButton(
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor:
                                        FlutterFlowTheme.of(context).primary,
                                    foregroundColor: Colors.white,
                                  ),
                                  onPressed: () async {
                                    final picker = ImagePicker();
                                    final pickedFile = await picker.pickImage(
                                        source: ImageSource.gallery);

                                    if (pickedFile != null) {
                                      File newGrayImage =
                                          await convertToGrayscale(
                                              File(pickedFile.path));
                                      final inputImage =
                                          InputImage.fromFilePath(
                                              newGrayImage.path);

                                      final textRecognizer = TextRecognizer(
                                          script: TextRecognitionScript.latin);
                                      final RecognizedText recognizedText =
                                          await textRecognizer
                                              .processImage(inputImage);
                                      textRecognizer.close();

                                      String newExtractedText =
                                          recognizedText.text;
                                      _parsePrayerTimes(newExtractedText);

                                      setState(() {
                                        grayImage = newGrayImage;
                                        _text = newExtractedText;
                                      });
                                    }
                                  },
                                  child: const Text("Change Image"),
                                ),
                              ),
                              const SizedBox(width: 10),
                              ElevatedButton(
                                style: ElevatedButton.styleFrom(
                                  backgroundColor:
                                      FlutterFlowTheme.of(context).primary,
                                  foregroundColor: Colors.white,
                                ),
                                onPressed: () async {
                                  final inputImage =
                                      InputImage.fromFilePath(grayImage.path);
                                  final textRecognizer = TextRecognizer(
                                      script: TextRecognitionScript.latin);
                                  final RecognizedText recognizedText =
                                      await textRecognizer
                                          .processImage(inputImage);

                                  extractedText = recognizedText.text;
                                  textRecognizer.close();

                                  _parsePrayerTimes(extractedText);

                                  setState(() {
                                    _text = extractedText;
                                  });

                                  pageController.nextPage(
                                    duration: const Duration(milliseconds: 300),
                                    curve: Curves.easeInOut,
                                  );
                                },
                                child: const Text("Process"),
                              ),
                            ],
                          ),
                        ],
                      ),

                      // Page 2: Editable prayer times
                      SizedBox(
                        height: 400, // ✅ Same fixed height
                        child: SingleChildScrollView(
                          child: Column(
                            children: _prayerOrder.map((prayer) {
                              final key = prayer['key']!;
                              final name = prayer['name']!;
                              final controller = TextEditingController(
                                  text: _prayerTimes[key] ?? '');
                              return Padding(
                                padding:
                                    const EdgeInsets.symmetric(vertical: 8),
                                child: Row(
                                  children: [
                                    SizedBox(width: 80, child: Text(name)),
                                    const SizedBox(width: 10),
                                    Expanded(
                                      child: TextFormField(
                                        controller: controller,
                                        decoration: const InputDecoration(
                                          border: OutlineInputBorder(),
                                          hintText: "HH:mm",
                                        ),
                                        onChanged: (value) {
                                          _prayerTimes[key] = value;
                                        },
                                      ),
                                    ),
                                  ],
                                ),
                              );
                            }).toList(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),

                // Dots below
                actions: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: List.generate(2, (index) {
                      return Container(
                        margin: const EdgeInsets.symmetric(horizontal: 4),
                        width: 10,
                        height: 10,
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: currentPage == index
                              ? const Color.fromRGBO(15, 13, 161, 1)
                              : Colors.grey,
                        ),
                      );
                    }),
                  ),
                  const SizedBox(height: 10),
                ],
              );
            },
          );
        },
      );
    }
  }

  List<String> _setAlarms = [];

  Future<File> convertToGrayscale(File imageFile) async {
    final bytes = await imageFile.readAsBytes();
    img.Image? original = img.decodeImage(bytes);
    if (original == null) return imageFile;

    img.Image grayscale = img.grayscale(original);
    final grayPath = imageFile.path
        .replaceFirst('.jpg', '_gray.jpg')
        .replaceFirst('.png', '_gray.png');
    final newFile = File(grayPath);
    await newFile.writeAsBytes(img.encodeJpg(grayscale));
    return newFile;
  }

  /// ⬇️ Convert Arabic digits to English
  String convertArabicToEnglishDigits(String input) {
    const arabic = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'];
    const english = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
    for (int i = 0; i < arabic.length; i++) {
      input = input.replaceAll(arabic[i], english[i]);
    }
    return input;
  }

  /// ⬇️ Parse times & labels from OCR text
  void _parsePrayerTimes(String text) {
    final lines = text.split('\n');
    final times = <String>[];

    final Map<String, String> knownLabels = {
      "الفجر": "Fajr",
      "الظهر": "Dhuhr",
      "العصر": "Asr",
      "المغرب": "Maghrib",
      "العشاء": "Isha",
    };

    final timeRegex = RegExp(r'(\d{1,2})[:٫](\d{2})');

    for (final line in lines) {
      final cleanLine = convertArabicToEnglishDigits(line);
      final match = timeRegex.firstMatch(cleanLine);
      if (match != null) {
        final hour = match.group(1);
        final minute = match.group(2);
        times.add('$hour:$minute');
      }
    }

    bool foundLabeledTimes = false;
    for (final line in lines) {
      final cleanLine = convertArabicToEnglishDigits(line);
      for (var label in knownLabels.keys) {
        if (cleanLine.contains(label)) {
          final match = timeRegex.firstMatch(cleanLine);
          if (match != null) {
            final hour = match.group(1);
            final minute = match.group(2);
            _prayerTimes[knownLabels[label]!] = '$hour:$minute';
            foundLabeledTimes = true;
          }
        }
      }
    }

    if (!foundLabeledTimes && times.isNotEmpty) {
      for (int i = 0; i < times.length && i < _prayerOrder.length; i++) {
        _prayerTimes[_prayerOrder[i]['key']!] = times[i];
      }
    }
  }

  /// ⬇️ Show editable prayer time dialog
  void showEditPrayerTimesDialog() {
    final Map<String, TextEditingController> controllers = {
      for (var prayer in _prayerOrder)
        prayer['key']!: TextEditingController(
          text: _prayerTimes[prayer['key']!] ?? '',
        ),
    };

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text("Edit Prayer Times"),
        content: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: _prayerOrder.map((prayer) {
              return Padding(
                padding: const EdgeInsets.symmetric(vertical: 6),
                child: TextField(
                  controller: controllers[prayer['key']!],
                  decoration: InputDecoration(
                    labelText: prayer['name'],
                    border: const OutlineInputBorder(),
                  ),
                ),
              );
            }).toList(),
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text("Cancel"),
          ),
          ElevatedButton(
            onPressed: () {
              setState(() {
                for (var prayer in _prayerOrder) {
                  _prayerTimes[prayer['key']!] =
                      controllers[prayer['key']!]!.text.trim();
                }
              });
              Navigator.of(context).pop();
            },
            child: const Text("Save"),
          ),
        ],
      ),
    );
  }

  void showImagePreviewWithText(File image, String text) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text("Image & OCR Result"),
        content: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              if (_image != null)
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Image.file(_image!),
                ),
              const SizedBox(height: 20),
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Center(
                      child: ElevatedButton(
                        onPressed: () {
                          setState(() {
                            _text = _text.replaceAll(RegExp(r'[a-zA-Z]'), '');
                          });
                        },
                        child: const Text("Remove alphabets"),
                      ),
                    ),
                    const SizedBox(height: 20),
                    if (_text.isNotEmpty) ...[
                      GestureDetector(
                        onTap: showEditPrayerTimesDialog,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Text(
                              "Raw Extracted Text (Tap to edit times):",
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: Colors.blue,
                                decoration: TextDecoration.underline,
                              ),
                            ),
                            const SizedBox(height: 8),
                            Text(_text),
                            const SizedBox(height: 20),
                          ],
                        ),
                      ),
                    ],
                    if (_prayerTimes.isNotEmpty) ...[
                      const Text(
                        "Prayer Times:",
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 20,
                        ),
                      ),
                      const SizedBox(height: 10),
                      Column(
                        children: _prayerOrder.map((prayer) {
                          final time = _prayerTimes[prayer['key']];
                          return time != null
                              ? Padding(
                                  padding:
                                      const EdgeInsets.symmetric(vertical: 6.0),
                                  child: Row(
                                    children: [
                                      Text(
                                        "${prayer['name']}: ",
                                        style: const TextStyle(
                                          fontSize: 18,
                                          fontWeight: FontWeight.bold,
                                        ),
                                      ),
                                      Text(
                                        time,
                                        style: const TextStyle(fontSize: 18),
                                      ),
                                    ],
                                  ),
                                )
                              : const SizedBox.shrink();
                        }).toList(),
                      ),
                    ],
                    ElevatedButton(
                      onPressed: () {
                        setPrayerAlarms();
                      },
                      child: const Text("Set Alarm"),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text("Close"),
          ),
        ],
      ),
    );
  }

  final scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  void initState() {
    super.initState();
    _model = createModel(context, () => DashboardModel());

    WidgetsBinding.instance.addPostFrameCallback((_) => safeSetState(() {}));
    _loadSetAlarms();
    FirebaseAuth.instance.signInAnonymously();
  }

  Future<void> _loadSetAlarms() async {
    final prefs = await SharedPreferences.getInstance();
    final savedAlarms = prefs.getStringList('set_alarms') ?? [];

    setState(() {
      _setAlarms = savedAlarms;
    });
  }

  @override
  void dispose() {
    _model.dispose();

    super.dispose();
  }

  Widget _drawerCard(
    BuildContext context, {
    required IconData icon,
    required String title,
    required String subtitle,
    required VoidCallback onTap,
  }) {
    final theme = FlutterFlowTheme.of(context);
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      child: Card(
        color: theme.secondaryBackground,
        elevation: 4,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16),
        ),
        child: ListTile(
          leading: CircleAvatar(
            backgroundColor:
                FlutterFlowTheme.of(context).primary.withOpacity(0.15),
            child: Icon(icon, color: FlutterFlowTheme.of(context).primary),
          ),
          title: Text(
            title,
            style: TextStyle(fontWeight: FontWeight.w600),
          ),
          subtitle: Text(subtitle),
          trailing: Icon(Icons.arrow_forward_ios, size: 16),
          onTap: onTap,
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = FlutterFlowTheme.of(context);
    return GestureDetector(
        onTap: () {
          FocusScope.of(context).unfocus();
          FocusManager.instance.primaryFocus?.unfocus();
        },
        child: Scaffold(
            key: scaffoldKey,
            backgroundColor: FlutterFlowTheme.of(context).primaryBackground,
            // floatingActionButton: Align(
            //   alignment: AlignmentDirectional(1.0, 1.0),
            //   child: Row(
            //     crossAxisAlignment: CrossAxisAlignment.end,
            //     mainAxisAlignment: MainAxisAlignment.end,
            //     children: [
            //       FloatingActionButton(
            //         onPressed: () {
            //           Navigator.of(context).push(
            //               MaterialPageRoute(builder: (context) => ImageToText()));
            //         },
            //         backgroundColor: FlutterFlowTheme.of(context).primary,
            //         elevation: 8.0,
            //         child: Icon(
            //           Icons.alarm,
            //           color: FlutterFlowTheme.of(context).info,
            //           size: 24.0,
            //         ),
            //       ),
            //       SizedBox(
            //         width: 20,
            //       ),
            //       FloatingActionButton(
            //         onPressed: _showImageSourceDialog,
            //         backgroundColor: FlutterFlowTheme.of(context).primary,
            //         elevation: 8.0,
            //         child: Icon(
            //           Icons.camera_alt,
            //           color: FlutterFlowTheme.of(context).info,
            //           size: 24.0,
            //         ),
            //       ),
            //     ],
            //   ),
            // ),
            drawer: Drawer(
              backgroundColor: theme.primaryBackground,
              child: ListView(
                padding: EdgeInsets.zero,
                children: [
                  /// 🔹 Drawer Header
                  DrawerHeader(
                    decoration: BoxDecoration(
                      color: FlutterFlowTheme.of(context).primary,
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // Icon(Icons.mosque, color: Colors.white, size: 40),
                        SizedBox(height: 30),
                        Text(
                          AppLocalizations.of(context)!.appName,
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 26,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),
                  ),

                  /// 🔹 About Us Card
                  _drawerCard(
                    context,
                    icon: Icons.info_outline,
                    title: AppLocalizations.of(context)!.aboutUs,
                    subtitle: AppLocalizations.of(context)!.aboutUsSubtitle,
                    onTap: () {
                      Navigator.pop(context);
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (_) => AboutUsWidget()),
                      );
                    },
                  ),

                  /// 🔹 Contact Us Card
                  _drawerCard(
                    context,
                    icon: Icons.call_outlined,
                    title: AppLocalizations.of(context)!.contactUs,
                    subtitle: AppLocalizations.of(context)!.contactUsSubtitle,
                    onTap: () {
                      Navigator.pop(context);
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (_) => ContactUsWidget()),
                      );
                    },
                  ),

                  /// 🔹 Language Card
                  _drawerCard(
                    context,
                    icon: Icons.language_outlined,
                    title: AppLocalizations.of(context)!.language,
                    subtitle: AppLocalizations.of(context)!.languageSubtitle,
                    onTap: () {
                      Navigator.pop(context);
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (_) => const LanguagePage()),
                      );
                    },
                  ),
                ],
              ),
            ),
            appBar: AppBar(
              backgroundColor: FlutterFlowTheme.of(context).primary,
              automaticallyImplyLeading: true,
              title: Align(
                alignment: AlignmentDirectional(0.0, 0.0),
                child: Text(
                  AppLocalizations.of(context)!.appName,
                  style: FlutterFlowTheme.of(context).headlineMedium.override(
                        font: GoogleFonts.inter(
                          fontWeight: FlutterFlowTheme.of(context)
                              .headlineMedium
                              .fontWeight,
                          fontStyle: FlutterFlowTheme.of(context)
                              .headlineMedium
                              .fontStyle,
                        ),
                        color: FlutterFlowTheme.of(context).alternate,
                        fontSize: 30.0,
                        letterSpacing: 0.0,
                        fontWeight: FlutterFlowTheme.of(context)
                            .headlineMedium
                            .fontWeight,
                        fontStyle: FlutterFlowTheme.of(context)
                            .headlineMedium
                            .fontStyle,
                      ),
                ),
              ),
              actions: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: IconButton(
                      onPressed: () {
                        _showImageSourceDialog();
                      },
                      icon: Icon(Icons.camera_alt)),
                )
              ],
              centerTitle: true,
              elevation: 2.0,
            ),
            body: SafeArea(
              top: true,
              child: _setAlarms.isEmpty
                  ? Padding(
                      padding: const EdgeInsets.all(20),
                      child: Center(
                        child: Text(
                          AppLocalizations.of(context)!.clickSnapSetAlarms,
                          style: const TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                            color: Colors.white,
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    )
                  : SingleChildScrollView(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const SizedBox(height: 20),

                          // 🔹 Prayer Clock Design UI (like your image)
                          // PrayerClockCircle(),

                          const SizedBox(height: 20),

                          // 🔹 Image at top

                          const SizedBox(height: 10),

                          // 🔹 Alarm list
                          ListView.builder(
                            physics: const NeverScrollableScrollPhysics(),
                            shrinkWrap: true,
                            itemCount: _setAlarms.length,
                            itemBuilder: (context, index) {
                              return Padding(
                                padding: const EdgeInsets.only(
                                    right: 15, left: 15, bottom: 10, top: 5),
                                child: Card(
                                  color: Color(0xFF0A1D37),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(20),
                                  ),
                                  child: ListTile(
                                    leading: const Icon(Icons.alarm,
                                        color: Colors.white),
                                    title: Text(
                                      _setAlarms[index],
                                      style:
                                          const TextStyle(color: Colors.white),
                                    ),
                                    onTap: () async {
                                      final parts =
                                          _setAlarms[index].split(':');
                                      if (parts.length >= 2) {
                                        final hourPart =
                                            int.tryParse(parts[1].trim()) ?? 0;
                                        final minuteAndPeriod =
                                            parts[2].trim().split(' ');
                                        final minutePart =
                                            int.tryParse(minuteAndPeriod[0]) ??
                                                0;
                                        final period =
                                            minuteAndPeriod.length > 1
                                                ? minuteAndPeriod[1]
                                                : 'AM';

                                        int hour = hourPart;
                                        int minute = minutePart;

                                        if (period == 'PM' && hour < 12)
                                          hour += 12;
                                        if (period == 'AM' && hour == 12)
                                          hour = 0;

                                        final AndroidIntent intent =
                                            AndroidIntent(
                                          action:
                                              'android.intent.action.SET_ALARM',
                                          arguments: <String, dynamic>{
                                            'android.intent.extra.alarm.HOUR':
                                                hour,
                                            'android.intent.extra.alarm.MINUTES':
                                                minute,
                                            'android.intent.extra.alarm.SKIP_UI':
                                                false,
                                          },
                                        );

                                        await intent.launch();
                                      }
                                    },
                                  ),
                                ),
                              );
                            },
                          ),
                        ],
                      ),
                    ),
            )));
  }
}

class PrayerQRScanner extends StatelessWidget {
  const PrayerQRScanner({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Scan QR"),
        backgroundColor: FlutterFlowTheme.of(context).primary,
      ),
      body: MobileScanner(
        onDetect: (barcode) {
          final String? code = barcode.barcodes.first.rawValue;

          if (code == null) return;

          Navigator.pop(context, code); // 🔥 VERY IMPORTANT
        },
      ),
    );
  }
}

// class PrayerClockCircle extends StatefulWidget {
//   final List<Map<String, dynamic>>? alarms; // Pass alarms from parent

//   const PrayerClockCircle({
//     Key? key,
//     this.alarms,
//   }) : super(key: key);

//   @override
//   State<PrayerClockCircle> createState() => _PrayerClockCircleState();
// }

// class _PrayerClockCircleState extends State<PrayerClockCircle> {
//   List<Map<String, String>> prayers = [
//     {'name': 'فجر', 'time': '05:30'},
//     {'name': 'ظہر', 'time': '12:45'},
//     {'name': 'عصر', 'time': '16:00'},
//     {'name': 'مغرب', 'time': '18:30'},
//     {'name': 'عشاء', 'time': '20:00'},
//     {'name': 'جمعہ', 'time': '13:00'},
//   ];

//   int currentPrayerIndex = 0;
//   double needleAngle = 0;

//   @override
//   void initState() {
//     super.initState();
//     _updateCurrentPrayer();
//     // Update every minute to check if prayer time has changed
//     Future.delayed(Duration.zero, () {
//       _startTimer();
//     });
//   }

//   void _startTimer() {
//     Future.delayed(const Duration(minutes: 1), () {
//       if (mounted) {
//         _updateCurrentPrayer();
//         _startTimer();
//       }
//     });
//   }

//   void _updateCurrentPrayer() {
//     // Get current time
//     final now = TimeOfDay.now();
//     final currentMinutes = now.hour * 60 + now.minute;

//     // Find which prayer time has passed and next is upcoming
//     int nextPrayerIndex = 0;

//     for (int i = 0; i < prayers.length; i++) {
//       final prayerTime = _parseTime(prayers[i]['time']!);
//       final prayerMinutes = prayerTime.hour * 60 + prayerTime.minute;

//       // If current time is before this prayer time, this is the next prayer
//       if (currentMinutes < prayerMinutes) {
//         nextPrayerIndex = i;
//         break;
//       }
//       // If we're past all prayers today, next is first prayer (Fajr)
//       if (i == prayers.length - 1) {
//         nextPrayerIndex = 0;
//       }
//     }

//     setState(() {
//       currentPrayerIndex = nextPrayerIndex;
//       // Needle always points to top (next prayer)
//       needleAngle = -pi / 2;
//     });
//   }

//   TimeOfDay _parseTime(String time) {
//     final parts = time.split(':');
//     return TimeOfDay(
//       hour: int.parse(parts[0]),
//       minute: int.parse(parts[1]),
//     );
//   }

//   // Reorder prayers so current prayer is first
//   List<Map<String, String>> _getReorderedPrayers() {
//     List<Map<String, String>> reordered = [];
//     for (int i = 0; i < prayers.length; i++) {
//       int index = (currentPrayerIndex + i) % prayers.length;
//       reordered.add(prayers[index]);
//     }
//     return reordered;
//   }

//   @override
//   Widget build(BuildContext context) {
//     double radius = 110;
//     double center = 150;
//     final reorderedPrayers = _getReorderedPrayers();

//     return Center(
//       child: Container(
//         width: 300,
//         height: 300,
//         decoration: BoxDecoration(
//           shape: BoxShape.circle,
//           gradient: RadialGradient(
//             colors: [Colors.white30, const Color(0xFF0A1D37)],
//             center: Alignment.center,
//             radius: 1.0,
//           ),
//         ),
//         child: Stack(
//           children: [
//             // Center Needle pointing to current prayer
//             Align(
//               alignment: Alignment.center,
//               child: Transform.rotate(
//                 angle: needleAngle,
//                 child: Column(
//                   mainAxisSize: MainAxisSize.min,
//                   children: [
//                     // Needle
//                     Container(
//                       width: 6,
//                       height: 70,
//                       decoration: BoxDecoration(
//                         color: Colors.amber,
//                         borderRadius: BorderRadius.circular(5),
//                         boxShadow: [
//                           BoxShadow(
//                             color: Colors.amber.withOpacity(0.5),
//                             blurRadius: 8,
//                             spreadRadius: 2,
//                           ),
//                         ],
//                       ),
//                     ),
//                     SizedBox(height: 50),
//                   ],
//                 ),
//               ),
//             ),

//             // Center circle
//             Align(
//               alignment: Alignment.center,
//               child: Container(
//                 width: 30,
//                 height: 30,
//                 decoration: BoxDecoration(
//                   shape: BoxShape.circle,
//                   border: Border.all(color: Colors.amber, width: 2),
//                   color: const Color(0xFF0A1D37),
//                   boxShadow: [
//                     BoxShadow(
//                       color: Colors.amber.withOpacity(0.3),
//                       blurRadius: 10,
//                       spreadRadius: 2,
//                     ),
//                   ],
//                 ),
//                 child: const Icon(
//                   Icons.star,
//                   size: 16,
//                   color: Colors.amber,
//                 ),
//               ),
//             ),

//             // Prayer circles - reordered so current is at top
//             for (int i = 0; i < reorderedPrayers.length; i++)
//               Positioned(
//                 left: center +
//                     radius *
//                         cos(2 * pi * i / reorderedPrayers.length - pi / 2) -
//                     30,
//                 top: center +
//                     radius *
//                         sin(2 * pi * i / reorderedPrayers.length - pi / 2) -
//                     30,
//                 child: Container(
//                   width: 60,
//                   height: 60,
//                   decoration: BoxDecoration(
//                     color: i == 0
//                         ? Colors.amber.shade100
//                         : const Color(0xFFDBD0D0),
//                     shape: BoxShape.circle,
//                     border: i == 0
//                         ? Border.all(color: Colors.amber, width: 3)
//                         : null,
//                     boxShadow: [
//                       BoxShadow(
//                         color: i == 0
//                             ? Colors.amber.withOpacity(0.4)
//                             : Colors.grey.shade400,
//                         blurRadius: i == 0 ? 8 : 4,
//                         offset: const Offset(2, 2),
//                       ),
//                     ],
//                   ),
//                   child: Center(
//                     child: Column(
//                       mainAxisAlignment: MainAxisAlignment.center,
//                       children: [
//                         Text(
//                           reorderedPrayers[i]['name']!,
//                           textAlign: TextAlign.center,
//                           style: TextStyle(
//                             fontSize: 12,
//                             fontWeight:
//                                 i == 0 ? FontWeight.w900 : FontWeight.bold,
//                             color:
//                                 i == 0 ? Colors.amber.shade900 : Colors.black,
//                           ),
//                         ),
//                         Text(
//                           reorderedPrayers[i]['time']!,
//                           textAlign: TextAlign.center,
//                           style: TextStyle(
//                             fontSize: 9,
//                             fontWeight: FontWeight.w500,
//                             color:
//                                 i == 0 ? Colors.amber.shade900 : Colors.black54,
//                           ),
//                         ),
//                       ],
//                     ),
//                   ),
//                 ),
//               ),
//           ],
//         ),
//       ),
//     );
//   }
// }

class AboutPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('About Page'),
      ),
      body: Center(
        child: Text(
          'This is About Page',
          style: TextStyle(fontSize: 18),
        ),
      ),
    );
  }
}
