// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_Jp6Ip8_jRvZ2tdG1Tdsa26myBqnBY8',
    appId: '1:494359488452:web:6c534aa89fa6255d4d6691',
    messagingSenderId: '494359488452',
    projectId: 'salahsnap-d2bf9',
    authDomain: 'salahsnap-d2bf9.firebaseapp.com',
    storageBucket: 'salahsnap-d2bf9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCPnAN4x7_-14w9-3mSUKpHSyab1oX2LM',
    appId: '1:494359488452:android:09026d969370180e4d6691',
    messagingSenderId: '494359488452',
    projectId: 'salahsnap-d2bf9',
    storageBucket: 'salahsnap-d2bf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfS1Gztde8LC4e2lwNAniblhuu-D2TUTQ',
    appId: '1:494359488452:ios:f3bf2383c6519e364d6691',
    messagingSenderId: '494359488452',
    projectId: 'salahsnap-d2bf9',
    storageBucket: 'salahsnap-d2bf9.firebasestorage.app',
    iosBundleId: 'com.salahsnap.com',
  );
}
